# fly.toml app configuration file generated for aibot3 on 2025-04-21T21:23:45Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'aibot3'
primary_region = 'jnb'

[build]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false       # Do not stop machines when idle
  auto_start_machines = true       # Start machines on demand (still useful)
  min_machines_running = 2         # Keep 2 machines always running
  processes = ['app']
