# fly.toml app configuration file generated for aibot2-cool-river-7434 on 2025-04-21T23:50:19+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'aibot2-cool-river-7434'
primary_region = 'jnb'

[build]

[[mounts]]
  source = 'app_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
