# fly.toml app configuration file
app = 'aibot3'
primary_region = 'jnb'

[build]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[http_service]
  internal_port = 8090
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[services]]
  internal_port = 8090
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.http_checks]]
    interval = 10000         # every 10 seconds
    timeout = 2000           # 2 seconds max wait
    grace_period = "10s"
    method = "GET"
    path = "/health"
    protocol = "http"
